### PR TITLE
Avoid <<- in tests

### PR DESCRIPTION
**Pull request by MichaelChirico**
Ran into an obscure issue in testing where `t2` wound up with a locked binding and `t2 <<-` failed.

This is probably a specific issue to my setup, but gets at why `<<-` is better avoided if possible -- it's hard to debug and cascading assignment can have hard-to-predict side effects. Instead, assigning to a specific environment makes it clearer where the object should be used.

IIUC, this also makes the tests more hermetic as testthat will clean up the variables defined within each test file.

### CODE REVIEW

**Comment by xrobin** [comment]
Hi Michael,

You are very right, assigning globally in tests is very sloppy and should be avoided. I like the change, using an enclosed environment so things can still be shared is very smart. I never thought of it.

I'm not sure why the checks are failing though. Did you run all the tests including the slow ones? I have a weird setup in pROC where I skip some of the tests that take too long (especially bootstrap stuff; otherwise the package would never make it to CRAN).

They can be enabled either by setting the `RUN_SLOW_TESTS=true` environment variable before running R CMD check, or setting `run_slow_tests <- TRUE`  before running `devtools::test()`.

**Comment by MichaelChirico** [comment]
I haven't tested anything locally. The failure looks correct, though I suspect there's a bug in the tests that's being exposed here.

https://github.com/xrobin/pROC/blob/edcd42d7f63210e51830e69b5528d968235edf37/tests/testthat/test-print.R#L10

IINM this is relying on the object being defined by `<<-` _AND_ that the tests happen to be run in alphabetical order by filename:

https://github.com/xrobin/pROC/blob/edcd42d7f63210e51830e69b5528d968235edf37/tests/testthat/test-power.roc.test.R#L156

Looking elsewhere in the file, I am guessing that `r.ndka.partial1` is a more appropriate choice, since that's defined in a helper and thus intentionally available to all tests:

https://github.com/xrobin/pROC/blob/edcd42d7f63210e51830e69b5528d968235edf37/tests/testthat/helper-rocs.R#LL11C20-L11C20

PS I noticed a bunch of other warnings being thrown that make it a bit harder to debug issues like this since we have to wade through more output. I filed those warnings as separate issues.

**Comment by xrobin** [comment]
I've removed (most of) the warnings (in the develop branch). (Only the one about aes_string remains, as I don't know how to refactor it yet).

The reason I did that in early days was so data could be re-used for further tests. Probably before I realized I could use "helper" files.

It might be that some of these assignments would be best moved to helpers (or maybe already exist there).

**Comment by MichaelChirico** [comment]
Looks like we can use the helper-defined object, just needed to adjust the expected output to match.

**Comment by xrobin** [comment]
Excellent, thanks a lot for your contribution!

**Comment by xrobin** [comment]
Do you need this to be released soon or can it wait until the next regular release? (which isn't planned yet, so may take a while to come).

**Comment by MichaelChirico** [comment]
no rush at all, take your time!

**Comment by xrobin** [comment]
Turned out I needed an emergency fix for CRAN so the fixes are out now.

**Pull request merged**
